### ISSUE TITLE
Original title

### ISSUE THREAD

**Issue by maverick74** [tfonteyn/NeverTooManyBooks#13]
Is there an original title field?

(I can't find it!!!)

If there isn't... I would like to suggest adding it.

...IF YOU think it makes sense!!!

**Comment by tfonteyn** [comment]
IF YOU think it makes sense!!!

It's been on my personal TODO list since forever :)  I ***need*** it, so YES it makes perfect sense :)

I've been toying with just an "original title" but in combination with another field to indicate the original language.
Doing both takes quite a bit of screen space on my old 5" phone.

I think I will compromise and add a simple "original title" for now and decided on more later.
I'll plan to include this in a 4.4 release soonish.

**Comment by tfonteyn** [comment]
which reminds me... I took your suggestion on adding default languages (and format+colors) and implemented it.
 It'll be in the 4.4 as well.

**Comment by tfonteyn** [comment]
and here is [4.4.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v4.4.0)
