### ISSUE TITLE
Sort by number of pages

### ISSUE THREAD

**Issue by zettelmuseum** [tfonteyn/NeverTooManyBooks#18]
Hello,
I don't see a sorting option for number of pages, could you maybe add this?

Also, in my custom book listing style, i have enabled author and publisher, but only author is showing, maybe this is a bug?

edit:
one more thing. sometimes when adding books by title search, i get a book in a different language. is there a way to specify language?

Nice app, keep on going!

**Comment by tfonteyn** [comment]
Hi,

Glad you like it :)

Could I please ask to log different issues for different questions? It's easier to keep track of them for everyone.

Let's keep this issue for "number of pages", and I created #19 and #20 for the others. You'll need to subscribe to those to get updates.

This "number of pages" enhancement is really 2 things:

Add the page-count as a displayable field on the book-level in the list; i.e in the style configuration "Book details shown in the list" ==> Sure, easy to do and I will include this in the next update.

Add a group for Page-Count. Again, easy to do, but it would not be very useful I fear.
Let me explain:

The number-of-pages field is deliberately a text field (as opposed to a number). This was done to support descriptions like "foreword xv pages,  182 pages" which can often be found on the source-web-sites.

This would mean that:

1. Sorting is based on the alphabet, and not on the amount of pages (as a number)
2. content like "foreword xv ..." would always be sorted as coming after all pure-number descriptions.
3. numbers would not be sorted as actual number, but again as text.
   I mean:   you would get for example "67", "612" , "89", "900"  because "89" sorts alphabetically after "612".
4. Page count would show as a level, a group, in the list. You would probably end up with each time a group with one book in it (unless 2 books have an identical page count)

**Comment by zettelmuseum** [comment]
I see. I would really like to se the largest books in my collection, though.

**Comment by tfonteyn** [comment]
Hi,

It's going to take some time, but the 5.0 release will provide a lot of new sorting options.
Points 1..3 my previous comment will still be true but nr 4 will no longer be true which will make this type of sorting at least usable (but not perfect)

**Comment by tfonteyn** [comment]
[5.0.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v5.0.0) is now out.
