### ISSUE TITLE
Calibre Update Causes Duplicates

### ISSUE THREAD

**Issue by Humam-Hamdan** [tfonteyn/NeverTooManyBooks#27]
Hi again : )
When I use "New and Updated" (I'm revamping my library since why not), it causes the entries to duplicate, is there a way to easily remove the old entries? Or even better, if the app automatically updates them?

**Comment by tfonteyn** [comment]
>  entries to duplicate,

I haven't seen that happen in my own setup - I'll run some tests.

> easily remove the old entries

I've thought about adding a "delete all" option to the grouping rows but been reluctant as (even with confirm dialog) mistakes happen to easily. I'll have another think though.

Both of these will need to wait until next week probably. I really want the 5.1 out as Android 14 is now available to the public (see #23)

**Comment by Humam-Hamdan** [comment]
Yep of course, it isn't urgent, i just have to note what i changed and delete all the other books : )

**Comment by tfonteyn** [comment]
I managed to reproduce this but only for books which were added to Calibre on the same day as I do an sync import to NTMB twice.

In other words, I have:
- "yesterday" so to speak, I had 10 books in Calibre.
- "today" I add 2 books to calibre
- "today" I do a sync/import "All books" and end up with 12 books in NTMB (so far so good)
- I then syn/import again, and select "New and updated..." and yes, those 2 latter books are duplicated.  Each time I repeat this, I get 2 more duplicates.

I'll run another test tomorrow to see if I still get duplicates or not.

Can you confirm this is what you where seeing?

I made some changes last summer and I fear a bug got in... and I never noticed because my calibre server is not used a lot.

**Comment by tfonteyn** [comment]
in fact... I believe I've found the issue. First tests are running fine now, but I want to do a full 2-way test. That'll be for tomorrow or so.

**Comment by Humam-Hamdan** [comment]
>Can you confirm this is what you where seeing?

this is it.

**Comment by tfonteyn** [comment]
and here you go [NeverTooManyBooks-5.1.1.apk](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.1.1/NeverTooManyBooks-5.1.1.apk)

**Comment by Humam-Hamdan** [comment]
now it won't change unless i changes something in the metadata of the book, right?

**Comment by tfonteyn** [comment]
Calibre provides a "last-updated" datetime-stamp. And NTMB has it's own "last-update".
So during a sync, those two timestamps are compared. What exactly is changed it not tracked by either though.

The cut-off date ("Only import books modified since") is just a way to speed up syncs.
