### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by skeptronus** [tfonteyn/NeverTooManyBooks#30]
App wasn't used for some time, 2/3 subsequent updates were installed from fdroid. Crash on launch.
[ntmb-debug.zip](https://github.com/tfonteyn/NeverTooManyBooks/files/13522626/ntmb-debug.zip)
[ntmb-crash.txt](https://github.com/tfonteyn/NeverTooManyBooks/files/13522627/ntmb-crash.txt)

**Comment by tfonteyn** [comment]
Hello,

I've found and fixed this issue. It only affects upgrades across multiple versions which, I admit, don't extensively test.

It's fixed in the new release:  [5.2.3](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.2.3/NeverTooManyBooks-5.2.3.apk)

Just upgrade your current version and it will be straightened out.

Edit: 5.2.3 links

Sorry about this :(

**Comment by skeptronus** [comment]
That was quick ;)
Thank you very much!

**Comment by tfonteyn** [comment]
even quicker... 5.2.3 ... today's lesson: do not release when still half-sleeping....  ouch....

**Comment by skeptronus** [comment]
No way! 
Give it (and yourself) a rest :)
