### ISSUE TITLE
Grid view improvement 

### ISSUE THREAD

**Issue by lucastucious** [tfonteyn/NeverTooManyBooks#32]
Hi there ! Wonderful app ! 

I'm quite almost satisfied with the "customizable views", but the grid mode is lacking. I like to view my books as a "waterfall of cover" and edit from here. 

But at this time we cannot remove the dashed button, and the cover are small, however I do increase the cover size slider.

Is this something you plan to improve?

**Comment by tfonteyn** [comment]
Thanks!

Yes, I was not happy with the little-buttons under each cover either. It was a bit of a "good-enough-for-now" because I have a book to read :)

Tap the cover to a) zoom, or b) open the details screen 
=> this is configurable in the options for the style (just mentioning for completeness as I think you already found this)

The 3dot menu; I need to:
1. re-add a "long-press" on the cover to bring up the book-menu.
2. add an option to show/hide the 3dot button (for people who don't like long-press)

Small covers:
Correct, the slider is only applicable to the list-mode. At the time, I didn't pay to much attention to it.
But yes, being able to resize in grid-mode would be better.

So thanks for pushing this back to my attention.

I'm hoping to get back to these in a short while - the holiday season disrupted things.

**Comment by tfonteyn** [comment]
and here you go [5.3.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v5.3.0/NeverTooManyBooks-5.3.0.apk)

Button/long-click for the menu is now customizable.
The cover-sizing is applied in grid as well now.
