### ISSUE TITLE
[Feature Request] Add Deutsche National Bibliothek (DNB) to websources

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#63]
DNB is the official central archiving library in Germany. Every book, music, published in Germany will be archived, that's their mission.

Aside the clasic opac (online public access catalog) search at portal.dnb.de/opac there is a new and more convenient search page at katalog.dnb.de/DE/home.html 

regards
thomas

**Comment by tfonteyn** [comment]
A quick proof of concept with the 'beta' shows this site will work.
Meaning, I now/already have a basic search-by-isbn engine for the site. 

I'm a bit reluctant to take it further for the moment though:
- if I would use the seemingly more complete opac access, it might be a waste of time as they are replacing it with the new search page.
- the new searchpage is a beta, so we can expect changes which might break the app's parsing. No big deal, but it could result in bad user experience, and a rush on my behalf to update the app with a modified parser.

Notes:
I've used "978-3-453-32189-2" as a test:

 - "Titel"
   "Nemesis : Roman / Isaac Asimov ; deutsche Übersetzung von Irene Holicki"
   To get the actual title, I split on "/" and cut off the ": Roman".
   Other books might/will likely need other types are processing.
   I'll need (lots of) examples to try and cover all/most formats.

- "Beteiligt": this is not to bad, a bit annoying to parse, but fairly structured.

- "Erschienen"
  "München: Wilhelm Heyne Verlag  01/2023"
  I split twice, once on the ":" and one on the (invisible) line-break for the date.
  The big assumption here is of course that part-2 is the actual publisher.
  Again, I'll need a lot of examples to make sure parsing is getting the correct info

Other fields of interest:

Prices... I suppose less important from a library site, but only on the opac page.

Reihe/Beziehungen: no series-number

A description/synopsis is only available on the opac page (Weiterführende Informationen) which also contains a link to an "[Inhaltsverzeichnis]" which is sadly not structured at all (it's an OCR scan)

I'm happy to work on this, but I'll need examples which:
- use different formats for the title field
- potentially the same for the publisher
- ISBN's which return **more-than-one-result**. This is important as websites usually show a list of the results, from which I then have to construct a second request to get the actual book.

And as stated, their site is beta, so an app release will be delayed.


PS: it was raining badly today, hence my quick response  :-(

**Comment by tfonteyn** [comment]
the title field can be a real mess.... an example I cam across:

"Totholz : Was vergraben ist, ist nicht vergessen. Kriminalroman | Nummer 1 SPIEGEL Bestseller-Autor / Andreas Föhr"

And this is from a LIBRARY.....

**Comment by tfonteyn** [comment]
I did a little more work on this, and tried some more samples. I just grabbed some ISBN's from the front page of Thalia in different categories, and looked them up on DNB.

I improved on the titles by getting it from the top of the page rather than from the data table.

 1. 978-3-453-32189-2 Nemesis : Roman
 2. 978-3-426-22668-1 Totholz : Was vergraben ist, ist nicht vergessen. Kriminalroman | Nummer 1 SPIEGEL Bestseller-Autor
3. 978-3-453-44215-3 Wenn sie wüsste : Thriller
4. 978-3-551-03302-4 Das kleine Wir im Kindergarten
5. 978-3-499-01410-9 Brüssel sehen und sterben : wie ich im Europaparlament meinen Glauben an (fast) alles verloren habe
6. 978-3-96584-423-0 Der Glukose-Masterplan

I used more book examples, but they all fit the above patterns. What I did not do is look for any older books, mainly because I don't really know any native-language german authors; well, except Karl May, a childhood favourite of mine :-)

The suffixes  1. ": Roman" and 3. " : Thriller" are annoying but acceptable I guess. Some efforts can be made to strip them off but I'd need more examples.

The nr 2 title is (luckily?) still the worst I've seen.

All other fields (author, pub. etc) are not that bad and quite usable (the publication data needs some guesswork, but ok)

As said, I'll take this slowly, letting their 'beta' site mature.

If you have more information, and sample data of "problematic" books, i.e. unusual titles etc etc... then please share them here.

**Comment by tfonteyn** [comment]
A quick update to let you know what's happening.

I've done more book lookups across different genres, and only found one additional suffix (as described above) to strip automatically. It seems the only genres the website knows are: 

> Roman, Thriller, Psychothriller, Kriminalroman

A bit strange, they use those suffixes while for example science-fiction is just listed as "Roman".

Non-fiction books don't seem to use any such suffixes (which makes it easier of course).

I'm looking to release 6.2 later this week, but I'm still somewhat reluctant to include the DNB site. I really need some more examples of  "problematic" books.
If you could collect such that would be really helpful.

I also noticed some more fields being available (maybe newly added? or I just did not see them earlier?) so I'll need to expand the parsing anyhow.

**Comment by coastgnu** [comment]
>  I really need some more examples of "problematic" books.

I'm just in a bigger makeover of my apartment. So I will find time at the weekend. Having 1k of books I should find some.

Momenteel ben ik mijn appartement aan het renoveren. Vanaf dit weekend ga ik er tijd voor maken. Met 1k-boeken zou ik iets moeten vinden.

regards 
thomas

**Comment by tfonteyn** [comment]
I just checked the dnb data parsing... seems they are still making changes. I expanded my parsing a little, but fear we should wait for some more time for them to stabilize.

**Comment by coastgnu** [comment]
Library people adore nifty tools like bibtex and others.

So it might be a good idea to let them know that you work on dnb-search in ntmb!

I would bet they will put you on their inner circle, at least when it comes to plans of their roadmap!

**Comment by tfonteyn** [comment]
Better not. Website admins don't like robots/scraping

**Comment by coastgnu** [comment]
OK, you'r right, that's a point!

But librarians do and its  dnb's official job to list all books published in Germany and to offer this information.

Might it be an idea to ask dnb officials
'behind the courtain' to get their position to this point?

AFAIK heads of University Libraries/Librarians are very positive when it comes to public access to dnb, vlb and other public access catalgues. At least the head(s) of the University libraries I know.

**Comment by tfonteyn** [comment]
I've added it to the new release [6.3.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v6.3.0)

As always, if there are any problems, just log a new issue with details on which book you're looking up and I'll look into it.

**Comment by coastgnu** [comment]
Yippiee! 

Thanks a lot, vielen Dank, velen  Dank, bedankt heel mals!
