### ISSUE TITLE
[bug] crash after barcode scan and failed lookup

### ISSUE THREAD

**Issue by coastgnu** [tfonteyn/NeverTooManyBooks#64]
After scanning a barcode NTMB crashed after lookup the ISBN

[ntmb-crash-2024-06-16T09_16_20.119761.txt](https://github.com/user-attachments/files/15856502/ntmb-crash-2024-06-16T09_16_20.119761.txt)

thanks in advance
thomas

**Comment by tfonteyn** [comment]
I think I can see where it crashes - seems to lack an Author while editing the table.
But (in theory) an entry in that table cannot exist without an Author.

What is the ISBN you did a lookup on?

**Comment by coastgnu** [comment]
Katja Diehl; Auto Korrektur - Mobilität für eine lebenswerte Welt; S. Fischer Verlag; ISBN 9783103971422; €(D) 18,00

**Comment by tfonteyn** [comment]
excellent - it's as I expected. I reproduced and confirmed. This is due to bad-data coming from OpenLibrary.

I have in fact already fixed this with a workaround (sanity-check for a missing author) after I looked at your report.
I do want see if I can find out **why** openlibrary is sending bad-data for this book and check if I can create a more permanent solution.

More later today.

**Comment by tfonteyn** [comment]
here you go: [6.1.1](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.1/NeverTooManyBooks-6.1.1.apk)
